### ISSUE TITLE
can not preload pg_search

### ISSUE THREAD

**Issue by Shercode** [Vonng/pigsty#481]
meta=# CREATE EXTENSION pg_search;
ERROR:  pg_search must be loaded via shared_preload_libraries. Add 'pg_search' to shared_preload_libraries in postgresql.conf and restart Postgres.
meta=#
\q

lly@pg-meta-1:~/pigsty$ pg edit-config --force -p shared_preload_libraries='pg_stat_statements, auto_explain, pg_search'
Traceback (most recent call last):
  File "/usr/bin/patronictl", line 33, in <module>
    sys.exit(load_entry_point('patroni==4.0.4', 'console_scripts', 'patronictl')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/patroni/ctl.py", line 2106, in edit_config
    dcs = get_dcs(cluster_name, group)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/patroni/ctl.py", line 367, in get_dcs
    dcs = _get_dcs(config)
          ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/patroni/dcs/__init__.py", line 137, in get_dcs
    return dcs_class(config[name], get_mpp(config))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/patroni/dcs/etcd3.py", line 665, in __init__
    super(Etcd3, self).__init__(config, mpp, PatroniEtcd3Client,
  File "/usr/lib/python3/dist-packages/patroni/dcs/etcd.py", line 480, in __init__
    super(AbstractEtcd, self).__init__(config, mpp)
  File "/usr/lib/python3/dist-packages/patroni/dcs/__init__.py", line 1489, in __init__
    self._base_path = re.sub('/+', '/', '/'.join(['', config.get('namespace', 'service'), config['scope']]))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 2: expected str instance, NoneType found

**Comment by Shercode** [comment]
I have already installed it.

meta=# SELECT * FROM pg_available_extensions WHERE name LIKE '%search%';
   name    | default_version | installed_version |                        comment
-----------+-----------------+-------------------+-------------------------------------------------------
 pg_search | 0.13.0          |                   | pg_search: Full text search for PostgreSQL using BM25
(1 row)

**Comment by Vonng** [comment]
missing cluster name in patronictl command, you can try add it, or use the `pg edit-config` interactively: https://pigsty.io/docs/pgsql/admin/#config-cluster

**Comment by Shercode** [comment]
Thank you very much! I have fixed it following your guidance.

**Comment by Shercode** [comment]
Done!
